python .\week13a_challenge1.py "the quick red fox jumped over the lazy hound" --upper
python .\week13a_challenge1.py "the quick red fox jumped over the lazy hound" --lower
python .\week13a_challenge1.py "the quick red fox jumped over the lazy hound" --title
python .\week13a_challenge1.py "the quick red fox jumped over the lazy hound" --capitalize
python .\week13a_challenge1.py "the quick red fox jumped over the lazy hound" -u
python .\week13a_challenge1.py "the quick red fox jumped over the lazy hound" -l
python .\week13a_challenge1.py "the quick red fox jumped over the lazy hound" -t
python .\week13a_challenge1.py "the quick red fox jumped over the lazy hound" -c
python .\week13a_challenge1.py "THE QUICK RED FOX JUMPED OVER THE LAZY HOUND" --upper
python .\week13a_challenge1.py "THE QUICK RED FOX JUMPED OVER THE LAZY HOUND" --lower
python .\week13a_challenge1.py "THE QUICK RED FOX JUMPED OVER THE LAZY HOUND" --title
python .\week13a_challenge1.py "THE QUICK RED FOX JUMPED OVER THE LAZY HOUND" --capitalize
python .\week13a_challenge1.py "THE QUICK RED FOX JUMPED OVER THE LAZY HOUND" -u
python .\week13a_challenge1.py "THE QUICK RED FOX JUMPED OVER THE LAZY HOUND" -l
python .\week13a_challenge1.py "THE QUICK RED FOX JUMPED OVER THE LAZY HOUND" -t
python .\week13a_challenge1.py "THE QUICK RED FOX JUMPED OVER THE LAZY HOUND" -c
python .\week13a_challenge1.py "THE QUIck RED FoX JuMPED OVEr THE lazy houND" --upper
python .\week13a_challenge1.py "THE QUIck RED FoX JuMPED OVEr THE lazy houND" --lower
python .\week13a_challenge1.py "THE QUIck RED FoX JuMPED OVEr THE lazy houND" --title
python .\week13a_challenge1.py "THE QUIck RED FoX JuMPED OVEr THE lazy houND" --capitalize
python .\week13a_challenge1.py "THE QUIck RED FoX JuMPED OVEr THE lazy houND" -u
python .\week13a_challenge1.py "THE QUIck RED FoX JuMPED OVEr THE lazy houND" -l
python .\week13a_challenge1.py "THE QUIck RED FoX JuMPED OVEr THE lazy houND" -t
python .\week13a_challenge1.py "THE QUIck RED FoX JuMPED OVEr THE lazy houND" -c